/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;

import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.DefaultComboBoxModel;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author MarcusSkarud
 */
public class AndraTaBortAgent extends javax.swing.JFrame {
    
    private static InfDB db;
    /**
     * Creates new form andraAlien
     * @param db
     */
    public AndraTaBortAgent(InfDB db) {
        this.db = db;
        initComponents();
                
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        mibPortalLabel = new javax.swing.JLabel();
        sidLabel = new javax.swing.JLabel();
        skiljeStreck2 = new javax.swing.JSeparator();
        skiljeStreck1 = new javax.swing.JSeparator();
        bodyPanel = new javax.swing.JPanel();
        sokAgentmedNamnLabel = new javax.swing.JLabel();
        valjSoktAgentLabel = new javax.swing.JLabel();
        angeInfoLabel = new javax.swing.JLabel();
        nyAgentIDLabel = new javax.swing.JLabel();
        nyAgentNamnLabel = new javax.swing.JLabel();
        nyAgentLosenordLabel = new javax.swing.JLabel();
        nyAgentTelefonLabel = new javax.swing.JLabel();
        nyAgentOmradeLabel = new javax.swing.JLabel();
        nyAgentAnstallningsdatumLabel = new javax.swing.JLabel();
        sokAgentButton = new javax.swing.JButton();
        sokAgentTextField = new javax.swing.JTextField();
        valjSoktAgentBox = new javax.swing.JComboBox<>();
        skiljeStreck3 = new javax.swing.JSeparator();
        sparaUppdateradInfoButton = new javax.swing.JButton();
        nyAgentIDTextField = new javax.swing.JTextField();
        nyAgentNamnTextField = new javax.swing.JTextField();
        nyAgentLosenordTextField = new javax.swing.JTextField();
        nyAgentTelefonTextField = new javax.swing.JTextField();
        nyAgentAnstallningsdatumTextField = new javax.swing.JTextField();
        nyAgentOmradeBox = new javax.swing.JComboBox<>();
        skiljeStreck4 = new javax.swing.JSeparator();
        avbrytButton = new javax.swing.JButton();
        taBortAgentButton = new javax.swing.JButton();
        adminCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        sidPanel.setBackground(new java.awt.Color(40, 40, 40));

        headerPanel.setBackground(new java.awt.Color(80, 80, 80));
        headerPanel.setPreferredSize(new java.awt.Dimension(1095, 100));

        headerLabel.setBackground(new java.awt.Color(120, 120, 120));
        headerLabel.setFont(new java.awt.Font("Lucida Grande", 0, 28)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(200, 200, 200));
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("Men in Black - Sektor Skandinavien");

        mibPortalLabel.setBackground(new java.awt.Color(120, 120, 120));
        mibPortalLabel.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        mibPortalLabel.setForeground(new java.awt.Color(200, 200, 200));
        mibPortalLabel.setText("MiB-Portalen");

        sidLabel.setBackground(new java.awt.Color(120, 120, 120));
        sidLabel.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        sidLabel.setForeground(new java.awt.Color(200, 200, 200));
        sidLabel.setText("Ändra/ta bort agent");

        skiljeStreck2.setForeground(new java.awt.Color(200, 200, 200));

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(mibPortalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sidLabel)
                .addGap(39, 39, 39))
            .addComponent(headerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(skiljeStreck2, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(headerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(skiljeStreck2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mibPortalLabel)
                    .addComponent(sidLabel))
                .addContainerGap())
        );

        skiljeStreck1.setForeground(new java.awt.Color(250, 250, 250));

        bodyPanel.setBackground(new java.awt.Color(170, 170, 170));
        bodyPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        sokAgentmedNamnLabel.setForeground(new java.awt.Color(0, 0, 0));
        sokAgentmedNamnLabel.setText("Sök agent med namn:");

        valjSoktAgentLabel.setBackground(new java.awt.Color(250, 250, 250));
        valjSoktAgentLabel.setForeground(new java.awt.Color(0, 0, 0));
        valjSoktAgentLabel.setText("Välj agent att ändra:");

        angeInfoLabel.setBackground(new java.awt.Color(100, 100, 100));
        angeInfoLabel.setForeground(new java.awt.Color(250, 250, 250));
        angeInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        angeInfoLabel.setText("Ange uppdaterad information:");
        angeInfoLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        angeInfoLabel.setOpaque(true);

        nyAgentIDLabel.setForeground(new java.awt.Color(0, 0, 0));
        nyAgentIDLabel.setText("AgentID:");

        nyAgentNamnLabel.setForeground(new java.awt.Color(0, 0, 0));
        nyAgentNamnLabel.setText("Namn:");

        nyAgentLosenordLabel.setForeground(new java.awt.Color(0, 0, 0));
        nyAgentLosenordLabel.setText("Lösenord:");

        nyAgentTelefonLabel.setForeground(new java.awt.Color(0, 0, 0));
        nyAgentTelefonLabel.setText("Telefon:");

        nyAgentOmradeLabel.setForeground(new java.awt.Color(0, 0, 0));
        nyAgentOmradeLabel.setText("Område:");

        nyAgentAnstallningsdatumLabel.setForeground(new java.awt.Color(0, 0, 0));
        nyAgentAnstallningsdatumLabel.setText("Anställningsdatum:");

        sokAgentButton.setText("Sök agent");
        sokAgentButton.setPreferredSize(new java.awt.Dimension(83, 33));
        sokAgentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sokAgentButtonActionPerformed(evt);
            }
        });

        sokAgentTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sokAgentTextFieldActionPerformed(evt);
            }
        });

        valjSoktAgentBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---" }));
        valjSoktAgentBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valjSoktAgentBoxActionPerformed(evt);
            }
        });

        skiljeStreck3.setBackground(new java.awt.Color(250, 250, 250));
        skiljeStreck3.setForeground(new java.awt.Color(0, 0, 0));

        sparaUppdateradInfoButton.setText("Spara ändringar");
        sparaUppdateradInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sparaUppdateradInfoButtonActionPerformed(evt);
            }
        });

        nyAgentIDTextField.setEditable(false);

        nyAgentOmradeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---" }));

        skiljeStreck4.setBackground(new java.awt.Color(0, 0, 0));
        skiljeStreck4.setForeground(new java.awt.Color(250, 250, 250));

        avbrytButton.setText("Avbryt");
        avbrytButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avbrytButtonActionPerformed(evt);
            }
        });

        taBortAgentButton.setText("Ta bort agent");
        taBortAgentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taBortAgentButtonActionPerformed(evt);
            }
        });

        adminCheckBox.setBackground(new java.awt.Color(60, 60, 60));
        adminCheckBox.setForeground(new java.awt.Color(0, 0, 0));
        adminCheckBox.setText("Administratör");
        adminCheckBox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminCheckBox.setOpaque(false);

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(angeInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(skiljeStreck3)
                            .addGroup(bodyPanelLayout.createSequentialGroup()
                                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nyAgentNamnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nyAgentLosenordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                    .addComponent(nyAgentIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nyAgentLosenordTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(nyAgentIDTextField)
                                    .addComponent(nyAgentNamnTextField))
                                .addGap(18, 18, 18)
                                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nyAgentAnstallningsdatumLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nyAgentTelefonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nyAgentOmradeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(nyAgentTelefonTextField)
                                        .addComponent(nyAgentOmradeBox, 0, 140, Short.MAX_VALUE))
                                    .addComponent(nyAgentAnstallningsdatumTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(skiljeStreck4))
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(sparaUppdateradInfoButton)
                        .addGap(126, 126, 126)
                        .addComponent(taBortAgentButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(avbrytButton))
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sokAgentmedNamnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(valjSoktAgentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyPanelLayout.createSequentialGroup()
                                .addComponent(sokAgentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sokAgentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42))
                            .addComponent(valjSoktAgentBox, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(adminCheckBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sokAgentmedNamnLabel)
                            .addComponent(sokAgentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sokAgentButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(valjSoktAgentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valjSoktAgentBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(skiljeStreck3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(angeInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nyAgentIDLabel)
                            .addComponent(nyAgentIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nyAgentNamnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nyAgentNamnLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nyAgentLosenordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nyAgentLosenordLabel)))
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nyAgentTelefonTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nyAgentTelefonLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nyAgentOmradeLabel)
                            .addComponent(nyAgentOmradeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nyAgentAnstallningsdatumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nyAgentAnstallningsdatumLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(skiljeStreck4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sparaUppdateradInfoButton)
                    .addComponent(avbrytButton)
                    .addComponent(taBortAgentButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout sidPanelLayout = new javax.swing.GroupLayout(sidPanel);
        sidPanel.setLayout(sidPanelLayout);
        sidPanelLayout.setHorizontalGroup(
            sidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
            .addComponent(skiljeStreck1)
            .addGroup(sidPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sidPanelLayout.setVerticalGroup(
            sidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidPanelLayout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(skiljeStreck1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    @SuppressWarnings("unchecked")
    private void setOmradesBoxen(String omradesBenamning){
        DefaultComboBoxModel omradesBox = new DefaultComboBoxModel();
        try{
        ArrayList<String> omraden = db.fetchColumn("SELECT BENAMNING FROM OMRADE");
        for(String omradet : omraden ){
            omradesBox.addElement(omradet);
        }
        
        nyAgentOmradeBox.setModel(omradesBox);
        nyAgentOmradeBox.setSelectedItem(omradesBenamning);
        }
        catch(InfException undantag){
            System.out.println(undantag);
        }
        
    }    
    
        
    private void taBortAgentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taBortAgentButtonActionPerformed
        if (Validering.iDIfyllt(nyAgentIDTextField, valjSoktAgentBox)){
        }
        else{
            
            String[] agentSök = valjSoktAgentBox.getSelectedItem().toString().split(" ");
            int agentID = Integer.parseInt(agentSök[1]);

            deleteAgent(agentID);
            sokAgentTextField.setText("");
            sokAgentTextFieldActionPerformed(evt);
            valjSoktAgentBoxActionPerformed(evt);
            
        }
        
    }//GEN-LAST:event_taBortAgentButtonActionPerformed

    private void avbrytButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avbrytButtonActionPerformed
        AndraTaBortAgent.this.dispose();
    }//GEN-LAST:event_avbrytButtonActionPerformed

    private void sparaUppdateradInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sparaUppdateradInfoButtonActionPerformed
        if (Validering.iDIfyllt(nyAgentIDTextField, valjSoktAgentBox) && Validering.checkDatumFormat(nyAgentAnstallningsdatumTextField) &&
            Validering.textNotEmpty(nyAgentNamnTextField) && Validering.textNotEmpty(nyAgentLosenordTextField) &&
            Validering.textNotEmpty(nyAgentTelefonTextField) && Validering.textNotEmpty(nyAgentAnstallningsdatumTextField) &&
            Validering.checkPhoneLength(nyAgentTelefonTextField) && Validering.nameTextFieldLengthCheck(nyAgentNamnTextField) &&
            Validering.passwordTextFieldLengthCheck(nyAgentLosenordTextField))
            {

            String[] agentSök = valjSoktAgentBox.getSelectedItem().toString().split(" ");
            int agentID = Integer.parseInt(agentSök[1]);

            String adminStatus = "J";
            if(adminCheckBox.getSelectedObjects() == null){
                adminStatus = "N";
            }
            
            try{

                String omrade = db.fetchSingle("SELECT OMRADES_ID FROM OMRADE WHERE BENAMNING = '" + nyAgentOmradeBox.getSelectedItem().toString() + "'");
                
                deleteAgent(agentID);
                db.insert("INSERT INTO AGENT VALUES ( " + agentID + " , '" + nyAgentNamnTextField.getText().toString() + "' , '" + nyAgentTelefonTextField.getText().toString() + "' , '" + nyAgentAnstallningsdatumTextField.getText().toString() + "' , '" + adminStatus + "' , '" + nyAgentLosenordTextField.getText().toString() + "' , " + omrade + ")");
                

                JOptionPane.showMessageDialog(null, "Ändringarna sparade!");
                AndraTaBortAgent.this.dispose();

            }
            catch(Exception e){
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_sparaUppdateradInfoButtonActionPerformed

    @SuppressWarnings("unchecked")    
    private void valjSoktAgentBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valjSoktAgentBoxActionPerformed

        if (valjSoktAgentBox.getSelectedItem().equals("---")){
            rensaFalt();

        }
        else{

            try{
                String[] alienSök = valjSoktAgentBox.getSelectedItem().toString().split(" ");
                int agentID = Integer.parseInt(alienSök[1]);

                HashMap<String,String> valdAgent = db.fetchRow("SELECT * FROM AGENT WHERE AGENT_ID = " + agentID);

                String omrade = db.fetchSingle("SELECT BENAMNING FROM OMRADE WHERE OMRADES_ID = " + valdAgent.get("OMRADE"));

                setOmradesBoxen(omrade);

                nyAgentIDTextField.setText(valdAgent.get("AGENT_ID"));
                nyAgentNamnTextField.setText(valdAgent.get("NAMN"));
                nyAgentLosenordTextField.setText(valdAgent.get("LOSENORD"));
                nyAgentTelefonTextField.setText(valdAgent.get("TELEFON"));
                nyAgentAnstallningsdatumTextField.setText(valdAgent.get("ANSTALLNINGSDATUM"));
                if(new String(db.fetchSingle("SELECT ADMINISTRATOR FROM AGENT WHERE AGENT_ID =" + agentID)).equals("J")){
                    adminCheckBox.setSelected(true);
                }
                else {
                    adminCheckBox.setSelected(false);
                }
            }
            catch(InfException e){
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_valjSoktAgentBoxActionPerformed

    private void sokAgentTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sokAgentTextFieldActionPerformed
        setJComboBox(sokAgentTextField.getText().toString());
    }//GEN-LAST:event_sokAgentTextFieldActionPerformed

    private void sokAgentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sokAgentButtonActionPerformed
        sokAgentTextFieldActionPerformed(evt);
    }//GEN-LAST:event_sokAgentButtonActionPerformed

    @SuppressWarnings("unchecked")
    private void setJComboBox(String söktNamn){
        try{
        ArrayList<HashMap<String,String>> agent = db.fetchRows("SELECT * FROM AGENT WHERE NAMN = '" + söktNamn + "'");
        DefaultComboBoxModel söktAgentTillComboBox = new DefaultComboBoxModel();
        if (agent == null){
            söktAgentTillComboBox.addElement("---");
        }
        else{
            for(HashMap listaAgent : agent){
                String varjeAgent = "AgentID: " + listaAgent.get("AGENT_ID") + " | Telefon: " +  listaAgent.get("TELEFON") + " | Område: " +  db.fetchSingle("SELECT BENAMNING FROM OMRADE WHERE OMRADES_ID = " + listaAgent.get("OMRADE"));
                söktAgentTillComboBox.addElement(varjeAgent);
            }
        }
        valjSoktAgentBox.setModel(söktAgentTillComboBox);
        }
        catch(InfException undantag){
            System.out.println("Fel med databasen!" + undantag);
        }
        
    }
    @SuppressWarnings("unchecked")    
    private void deleteAgent(int agentID){
        
        try{
            String testSträng = db.fetchSingle("SELECT NAMN FROM ALIEN WHERE ANSVARIG_AGENT = " + agentID);
            if (testSträng != null){
                JOptionPane.showMessageDialog(null, "Agenten är ansvarig för en eller flera alien och kan därför inte tas bort!");
            }
            else{
                db.delete("DELETE FROM INNEHAR_UTRUSTNING WHERE AGENT_ID = " + agentID);
                db.delete("DELETE FROM INNEHAR_FORDON WHERE AGENT_ID = " + agentID);
                db.delete("DELETE FROM FALTAGENT WHERE AGENT_ID = " + agentID);
                db.delete("DELETE FROM KONTORSCHEF WHERE AGENT_ID = " + agentID);
                db.delete("DELETE FROM OMRADESCHEF WHERE AGENT_ID = " + agentID);            
                db.delete("DELETE FROM AGENT WHERE AGENT_ID = " + agentID);
            }
            
            
        }
        catch(InfException undantag){
            System.out.println("KUNDE INTE TA BORT AGENT! " + undantag);
        }
    }
    
    @SuppressWarnings("unchecked")     
    private void rensaFalt(){
        DefaultComboBoxModel tomBox = new DefaultComboBoxModel();
        tomBox.addElement("---");
        nyAgentIDTextField.setText("");
        nyAgentNamnTextField.setText("");
        nyAgentLosenordTextField.setText("");
        nyAgentTelefonTextField.setText("");
        nyAgentAnstallningsdatumTextField.setText("");
        adminCheckBox.setSelected(false);
        nyAgentOmradeBox.setModel(tomBox);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox adminCheckBox;
    private javax.swing.JLabel angeInfoLabel;
    private javax.swing.JButton avbrytButton;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel mibPortalLabel;
    private javax.swing.JLabel nyAgentAnstallningsdatumLabel;
    private javax.swing.JTextField nyAgentAnstallningsdatumTextField;
    private javax.swing.JLabel nyAgentIDLabel;
    private javax.swing.JTextField nyAgentIDTextField;
    private javax.swing.JLabel nyAgentLosenordLabel;
    private javax.swing.JTextField nyAgentLosenordTextField;
    private javax.swing.JLabel nyAgentNamnLabel;
    private javax.swing.JTextField nyAgentNamnTextField;
    private javax.swing.JComboBox<String> nyAgentOmradeBox;
    private javax.swing.JLabel nyAgentOmradeLabel;
    private javax.swing.JLabel nyAgentTelefonLabel;
    private javax.swing.JTextField nyAgentTelefonTextField;
    private javax.swing.JLabel sidLabel;
    private javax.swing.JPanel sidPanel;
    private javax.swing.JSeparator skiljeStreck1;
    private javax.swing.JSeparator skiljeStreck2;
    private javax.swing.JSeparator skiljeStreck3;
    private javax.swing.JSeparator skiljeStreck4;
    private javax.swing.JButton sokAgentButton;
    private javax.swing.JTextField sokAgentTextField;
    private javax.swing.JLabel sokAgentmedNamnLabel;
    private javax.swing.JButton sparaUppdateradInfoButton;
    private javax.swing.JButton taBortAgentButton;
    private javax.swing.JComboBox<String> valjSoktAgentBox;
    private javax.swing.JLabel valjSoktAgentLabel;
    // End of variables declaration//GEN-END:variables
}
