/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;

import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.DefaultComboBoxModel;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author MarcusSkarud
 */
public class AndraTaBortAlien extends javax.swing.JFrame {
    
    private static InfDB db;
    private boolean admin;
    /**
     * Creates new form andraAlien
     * @param db
     */
    public AndraTaBortAlien(InfDB db, boolean admin) {
        this.db = db;
        this.admin = admin;
        initComponents();
        initAndraAlien(admin);
        
                
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        mibPortalLabel = new javax.swing.JLabel();
        sidLabel = new javax.swing.JLabel();
        skiljeStreck2 = new javax.swing.JSeparator();
        skiljeStreck1 = new javax.swing.JSeparator();
        bodyPanel = new javax.swing.JPanel();
        soktAlienLabel = new javax.swing.JLabel();
        valjAlienLabel = new javax.swing.JLabel();
        angeInfoLabel = new javax.swing.JLabel();
        nyAlienIDLabel = new javax.swing.JLabel();
        nyAlienNamnLabel = new javax.swing.JLabel();
        nyAlienLosenordLabel = new javax.swing.JLabel();
        nyAlienTelefonLabel = new javax.swing.JLabel();
        nyAlienOmradeLabel = new javax.swing.JLabel();
        nyAlienPlatsLabel = new javax.swing.JLabel();
        nyAlienRegistreringsdatumLabel = new javax.swing.JLabel();
        nyAlienRasLabel = new javax.swing.JLabel();
        nyAlienExtraAttributLabel = new javax.swing.JLabel();
        nyAnsvarigAgentLabel = new javax.swing.JLabel();
        sokAlienTextField = new javax.swing.JTextField();
        nyAlienIDTextField = new javax.swing.JTextField();
        nyAlienNamnTextField = new javax.swing.JTextField();
        nyAlienLosenordTextField = new javax.swing.JTextField();
        nyAlienTelefonTextField = new javax.swing.JTextField();
        nyAlienRegistreringsdatumTextField = new javax.swing.JTextField();
        nyAlienExtraAttributTextField = new javax.swing.JTextField();
        valjSoktAlienBox = new javax.swing.JComboBox<>();
        nyAlienOmradesBox = new javax.swing.JComboBox<>();
        nyAlienPlatsBox = new javax.swing.JComboBox<>();
        nyAlienRasBox = new javax.swing.JComboBox<>();
        nyAlienAnsvarigAgentBox = new javax.swing.JComboBox<>();
        sokAlienButton = new javax.swing.JButton();
        sparaUppdateradInfoButton = new javax.swing.JButton();
        taBortAlienButton = new javax.swing.JButton();
        avbrytButton = new javax.swing.JButton();
        skiljeStreck3 = new javax.swing.JSeparator();
        skiljeStreck4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        sidPanel.setBackground(new java.awt.Color(40, 40, 40));

        headerPanel.setBackground(new java.awt.Color(80, 80, 80));
        headerPanel.setPreferredSize(new java.awt.Dimension(1095, 100));

        headerLabel.setBackground(new java.awt.Color(120, 120, 120));
        headerLabel.setFont(new java.awt.Font("Lucida Grande", 0, 28)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(200, 200, 200));
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("Men in Black - Sektor Skandinavien");

        mibPortalLabel.setBackground(new java.awt.Color(120, 120, 120));
        mibPortalLabel.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        mibPortalLabel.setForeground(new java.awt.Color(200, 200, 200));
        mibPortalLabel.setText("MiB-Portalen");

        sidLabel.setBackground(new java.awt.Color(120, 120, 120));
        sidLabel.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        sidLabel.setForeground(new java.awt.Color(200, 200, 200));
        sidLabel.setText("Ändra/ta bort alieninfo");

        skiljeStreck2.setForeground(new java.awt.Color(200, 200, 200));

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(mibPortalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sidLabel)
                .addGap(39, 39, 39))
            .addComponent(headerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(skiljeStreck2, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(headerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(skiljeStreck2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mibPortalLabel)
                    .addComponent(sidLabel))
                .addContainerGap())
        );

        skiljeStreck1.setForeground(new java.awt.Color(250, 250, 250));

        bodyPanel.setBackground(new java.awt.Color(170, 170, 170));
        bodyPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        soktAlienLabel.setForeground(new java.awt.Color(0, 0, 0));
        soktAlienLabel.setText("Sök alien med namn:");

        valjAlienLabel.setBackground(new java.awt.Color(250, 250, 250));
        valjAlienLabel.setForeground(new java.awt.Color(0, 0, 0));
        valjAlienLabel.setText("Välj alien att ändra:");

        angeInfoLabel.setBackground(new java.awt.Color(100, 100, 100));
        angeInfoLabel.setForeground(new java.awt.Color(250, 250, 250));
        angeInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        angeInfoLabel.setText("Ange uppdaterad information:");
        angeInfoLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        angeInfoLabel.setOpaque(true);

        nyAlienIDLabel.setForeground(new java.awt.Color(0, 0, 0));
        nyAlienIDLabel.setText("AlienID:");

        nyAlienNamnLabel.setForeground(new java.awt.Color(0, 0, 0));
        nyAlienNamnLabel.setText("Namn:");

        nyAlienLosenordLabel.setForeground(new java.awt.Color(0, 0, 0));
        nyAlienLosenordLabel.setText("Lösenord:");

        nyAlienTelefonLabel.setForeground(new java.awt.Color(0, 0, 0));
        nyAlienTelefonLabel.setText("Telefon:");

        nyAlienOmradeLabel.setForeground(new java.awt.Color(0, 0, 0));
        nyAlienOmradeLabel.setText("Område:");

        nyAlienPlatsLabel.setForeground(new java.awt.Color(0, 0, 0));
        nyAlienPlatsLabel.setText("Plats:");

        nyAlienRegistreringsdatumLabel.setForeground(new java.awt.Color(0, 0, 0));
        nyAlienRegistreringsdatumLabel.setText("Registreringsdatum:");

        nyAlienRasLabel.setForeground(new java.awt.Color(0, 0, 0));
        nyAlienRasLabel.setText("Ras:");
        nyAlienRasLabel.setPreferredSize(new java.awt.Dimension(91, 16));
        nyAlienRasLabel.setSize(new java.awt.Dimension(91, 16));

        nyAlienExtraAttributLabel.setForeground(new java.awt.Color(0, 0, 0));
        nyAlienExtraAttributLabel.setText("Antal boogies:");
        nyAlienExtraAttributLabel.setSize(new java.awt.Dimension(91, 16));

        nyAnsvarigAgentLabel.setForeground(new java.awt.Color(0, 0, 0));
        nyAnsvarigAgentLabel.setText("Ansvarig agent:");

        sokAlienTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sokAlienTextFieldActionPerformed(evt);
            }
        });

        nyAlienIDTextField.setEditable(false);

        nyAlienRegistreringsdatumTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nyAlienRegistreringsdatumTextFieldActionPerformed(evt);
            }
        });

        nyAlienExtraAttributTextField.setPreferredSize(new java.awt.Dimension(140, 24));

        valjSoktAlienBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---" }));
        valjSoktAlienBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valjSoktAlienBoxActionPerformed(evt);
            }
        });

        nyAlienOmradesBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---" }));
        nyAlienOmradesBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nyAlienOmradesBoxActionPerformed(evt);
            }
        });

        nyAlienPlatsBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---" }));

        nyAlienRasBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---" }));
        nyAlienRasBox.setPreferredSize(new java.awt.Dimension(140, 26));
        nyAlienRasBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nyAlienRasBoxActionPerformed(evt);
            }
        });

        nyAlienAnsvarigAgentBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---" }));

        sokAlienButton.setText("Sök alien");
        sokAlienButton.setPreferredSize(new java.awt.Dimension(83, 33));
        sokAlienButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sokAlienButtonActionPerformed(evt);
            }
        });

        sparaUppdateradInfoButton.setText("Spara ändringar");
        sparaUppdateradInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sparaUppdateradInfoButtonActionPerformed(evt);
            }
        });

        taBortAlienButton.setText("Ta bort alien");
        taBortAlienButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taBortAlienButtonActionPerformed(evt);
            }
        });

        avbrytButton.setText("Avbryt");
        avbrytButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avbrytButtonActionPerformed(evt);
            }
        });

        skiljeStreck3.setBackground(new java.awt.Color(250, 250, 250));
        skiljeStreck3.setForeground(new java.awt.Color(0, 0, 0));

        skiljeStreck4.setBackground(new java.awt.Color(0, 0, 0));
        skiljeStreck4.setForeground(new java.awt.Color(250, 250, 250));

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bodyPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(skiljeStreck3)
                            .addGroup(bodyPanelLayout.createSequentialGroup()
                                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(bodyPanelLayout.createSequentialGroup()
                                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(nyAlienRegistreringsdatumLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(nyAlienNamnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(nyAlienLosenordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(nyAlienIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(nyAlienTelefonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(nyAlienPlatsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(nyAlienRegistreringsdatumTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(nyAlienLosenordTextField)
                                            .addComponent(nyAlienTelefonTextField)
                                            .addComponent(nyAlienPlatsBox, 0, 140, Short.MAX_VALUE)
                                            .addComponent(nyAlienIDTextField)
                                            .addComponent(nyAlienNamnTextField)))
                                    .addGroup(bodyPanelLayout.createSequentialGroup()
                                        .addComponent(nyAlienOmradeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nyAlienOmradesBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(nyAlienExtraAttributLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nyAlienRasLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nyAnsvarigAgentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nyAlienExtraAttributTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nyAlienRasBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nyAlienAnsvarigAgentBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bodyPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(skiljeStreck4))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bodyPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(sparaUppdateradInfoButton)
                        .addGap(126, 126, 126)
                        .addComponent(taBortAlienButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(avbrytButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bodyPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(soktAlienLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valjAlienLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valjSoktAlienBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(bodyPanelLayout.createSequentialGroup()
                                .addComponent(sokAlienTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                .addComponent(sokAlienButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)))))
                .addContainerGap())
            .addComponent(angeInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soktAlienLabel)
                    .addComponent(sokAlienTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sokAlienButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valjAlienLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valjSoktAlienBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(skiljeStreck3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(angeInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nyAlienIDLabel)
                            .addComponent(nyAlienIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nyAlienNamnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nyAlienNamnLabel)
                            .addComponent(nyAlienExtraAttributLabel)
                            .addComponent(nyAlienExtraAttributTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nyAlienRasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nyAlienRasBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nyAlienLosenordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nyAlienLosenordLabel))
                    .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nyAnsvarigAgentLabel)
                        .addComponent(nyAlienAnsvarigAgentBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nyAlienTelefonTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nyAlienTelefonLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nyAlienOmradeLabel)
                    .addComponent(nyAlienOmradesBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nyAlienPlatsLabel)
                    .addComponent(nyAlienPlatsBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nyAlienRegistreringsdatumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nyAlienRegistreringsdatumLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(skiljeStreck4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sparaUppdateradInfoButton)
                    .addComponent(avbrytButton)
                    .addComponent(taBortAlienButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout sidPanelLayout = new javax.swing.GroupLayout(sidPanel);
        sidPanel.setLayout(sidPanelLayout);
        sidPanelLayout.setHorizontalGroup(
            sidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
            .addComponent(skiljeStreck1)
            .addGroup(sidPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        sidPanelLayout.setVerticalGroup(
            sidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidPanelLayout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(skiljeStreck1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("unchecked")    
    private void valjSoktAlienBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valjSoktAlienBoxActionPerformed

        if (valjSoktAlienBox.getSelectedItem().equals("---")){
            rensaFalt();

        }
        else{

            try{
                String[] alienSök = valjSoktAlienBox.getSelectedItem().toString().split(" ");
                int alienID = Integer.parseInt(alienSök[1]);
                String ras = alienSök[7];
                
                
                HashMap<String,String> valdAlien = db.fetchRow("SELECT * FROM ALIEN WHERE ALIEN_ID = " + alienID);
                setRasBoxen(ras, alienID);
                

                String plats = db.fetchSingle("SELECT BENAMNING FROM PLATS WHERE PLATS_ID = " + valdAlien.get("PLATS"));
                String omrade = db.fetchSingle("SELECT BENAMNING FROM OMRADE WHERE OMRADES_ID = (SELECT FINNS_I FROM PLATS WHERE PLATS_ID = " + valdAlien.get("PLATS") + ")");
                int finnsI = Integer.parseInt(db.fetchSingle("SELECT FINNS_I FROM PLATS WHERE PLATS_ID = " + valdAlien.get("PLATS")));
                
                
                setOmradesBoxen(omrade);
                setPlatsBoxen(plats, finnsI);
                setAnsvarigAgentBoxen(alienID, finnsI);
                
                nyAlienIDTextField.setText(valdAlien.get("ALIEN_ID"));
                nyAlienNamnTextField.setText(valdAlien.get("NAMN"));
                nyAlienLosenordTextField.setText(valdAlien.get("LOSENORD"));
                nyAlienTelefonTextField.setText(valdAlien.get("TELEFON"));
                nyAlienRegistreringsdatumTextField.setText(valdAlien.get("REGISTRERINGSDATUM"));
            }
            catch(InfException e){
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_valjSoktAlienBoxActionPerformed

    @SuppressWarnings("unchecked")    
    private void setRasBoxen(String ras, int alienID){
        DefaultComboBoxModel rasBox = new DefaultComboBoxModel();
        rasBox.addElement("Worm");
        rasBox.addElement("Boglodite");
        rasBox.addElement("Squid");
        nyAlienRasBox.setModel(rasBox);
        nyAlienRasBox.setSelectedItem(ras);
        
        try{
        if (ras.equals("Boglodite")){
        nyAlienExtraAttributLabel.setText("Antal boogies:");
        nyAlienExtraAttributLabel.setVisible(true);
        nyAlienExtraAttributTextField.setText(db.fetchSingle("SELECT ANTAL_BOOGIES FROM BOGLODITE WHERE ALIEN_ID =" + alienID));
        nyAlienExtraAttributTextField.setVisible(true);
        
        }
        else if (ras.equals("Squid")){
        nyAlienExtraAttributLabel.setText("Antal armar:");
        nyAlienExtraAttributLabel.setVisible(true);
        nyAlienExtraAttributTextField.setText(db.fetchSingle("SELECT ANTAL_ARMAR FROM SQUID WHERE ALIEN_ID =" + alienID));
        nyAlienExtraAttributTextField.setVisible(true);
        }
        else{
        nyAlienExtraAttributLabel.setVisible(false);
        nyAlienExtraAttributTextField.setVisible(false);
        }
        }
        catch(InfException undantag){
            System.out.println(undantag);
        }
    }
    
    @SuppressWarnings("unchecked")
    private void setOmradesBoxen(String omradesBenamning){
        DefaultComboBoxModel omradesBox = new DefaultComboBoxModel();
        try{
        ArrayList<String> omraden = db.fetchColumn("SELECT BENAMNING FROM OMRADE");
        for(String omradet : omraden ){
            omradesBox.addElement(omradet);
        }
        
        nyAlienOmradesBox.setModel(omradesBox);
        nyAlienOmradesBox.setSelectedItem(omradesBenamning);
        }
        catch(InfException undantag){
            System.out.println(undantag);
        }
        
    }
    
    @SuppressWarnings("unchecked")
    private void setPlatsBoxen(String platsBenamning, int finnsI){
        DefaultComboBoxModel platsBox = new DefaultComboBoxModel();
        
        try{
        ArrayList<String> platser = db.fetchColumn("SELECT BENAMNING FROM PLATS WHERE FINNS_I = " + finnsI);
       for(String platsen : platser ){
            platsBox.addElement(platsen);
        }
        
        nyAlienPlatsBox.setModel(platsBox);
        nyAlienPlatsBox.setSelectedItem(platsBenamning);
        }
        catch(InfException undantag){
            System.out.println(undantag);
        }
        
    }

    @SuppressWarnings("unchecked")    
    private void setAnsvarigAgentBoxen(int alienID, int finnsI){
        DefaultComboBoxModel agentBox = new DefaultComboBoxModel();
        
        try{
            String agentNamn = db.fetchSingle("SELECT NAMN FROM AGENT WHERE AGENT_ID = (SELECT ANSVARIG_AGENT FROM ALIEN WHERE ALIEN_ID = " + alienID + ")");
            ArrayList<String> agentIOmrade = db.fetchColumn("SELECT NAMN FROM AGENT WHERE OMRADE = " + finnsI);
            for(String agent : agentIOmrade ){
                agentBox.addElement(agent);
            }
        
            nyAlienAnsvarigAgentBox.setModel(agentBox);
            nyAlienAnsvarigAgentBox.setSelectedItem(agentNamn);
        }
            catch(InfException undantag){
            System.out.println(undantag);
        }
    }
    
    private void rensaFalt(){
        DefaultComboBoxModel tomBox = new DefaultComboBoxModel();
        tomBox.addElement("---");
        nyAlienIDTextField.setText("");
        nyAlienNamnTextField.setText("");
        nyAlienLosenordTextField.setText("");
        nyAlienTelefonTextField.setText("");
        nyAlienRegistreringsdatumTextField.setText("");
        nyAlienExtraAttributLabel.setVisible(false);
        nyAlienExtraAttributTextField.setVisible(false);
        nyAlienOmradesBox.setModel(tomBox);
        nyAlienPlatsBox.setModel(tomBox);
        nyAlienRasBox.setModel(tomBox);
        nyAlienAnsvarigAgentBox.setModel(tomBox);
    }
    
    
    private void initAndraAlien(boolean admin){
        nyAlienExtraAttributLabel.setVisible(false);
        nyAlienExtraAttributTextField.setVisible(false);
        if(!admin){
            taBortAlienButton.setVisible(false);
            sidLabel.setText("Ändra alieninfo");
        } 
    
    }
    
    private void sparaUppdateradInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sparaUppdateradInfoButtonActionPerformed
        if (Validering.iDIfyllt(nyAlienIDTextField, valjSoktAlienBox) && Validering.checkDatumFormat(nyAlienRegistreringsdatumTextField) &&
            Validering.textNotEmpty(nyAlienNamnTextField) && Validering.textNotEmpty(nyAlienLosenordTextField) &&
            Validering.textNotEmpty(nyAlienRegistreringsdatumTextField) && Validering.textNotEmpty(nyAlienExtraAttributTextField) && 
            Validering.checkPhoneLength(nyAlienTelefonTextField) && Validering.nameTextFieldLengthCheck(nyAlienNamnTextField) &&
            Validering.passwordTextFieldLengthCheck(nyAlienLosenordTextField)){
            
            String[] alienSök = valjSoktAlienBox.getSelectedItem().toString().split(" ");
            int alienID = Integer.parseInt(alienSök[1]);
            String gammalRas = alienSök[7];
            
            
            try{
                
                deleteAlien(alienID, gammalRas);
                String ansvarigAgent = db.fetchSingle("SELECT AGENT_ID FROM AGENT WHERE NAMN = '" + nyAlienAnsvarigAgentBox.getSelectedItem().toString() + "'");               
                String platsID = db.fetchSingle("SELECT PLATS_ID FROM PLATS WHERE BENAMNING = '" + nyAlienPlatsBox.getSelectedItem().toString() + "'");
                System.out.println(platsID);
                db.insert("INSERT INTO ALIEN VALUES ( " + alienID + " , '" + nyAlienRegistreringsdatumTextField.getText().toString() + "' , '" + nyAlienLosenordTextField.getText().toString() + "' , '" + nyAlienNamnTextField.getText().toString() + "' , '" + nyAlienTelefonTextField.getText().toString() + "' , " + platsID + " , " + ansvarigAgent + ")");
                System.out.println("Gick också!");    
                if (nyAlienRasBox.getSelectedItem().toString().equals("Squid") || nyAlienRasBox.getSelectedItem().toString().equals("Boglodite")){
                    db.insert("INSERT INTO " + nyAlienRasBox.getSelectedItem().toString() + " VALUES ( " + alienID + " , " + nyAlienExtraAttributTextField.getText().toString() + ")");
                }
                else{
                    db.insert("INSERT INTO " + nyAlienRasBox.getSelectedItem().toString() + " VALUES ( " + alienID + ")");
                }
                
                JOptionPane.showMessageDialog(null, "Ändringarna sparade!");
                AndraTaBortAlien.this.dispose();
                
            }
            catch(InfException e){
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_sparaUppdateradInfoButtonActionPerformed

    private void avbrytButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avbrytButtonActionPerformed
        AndraTaBortAlien.this.dispose();
    }//GEN-LAST:event_avbrytButtonActionPerformed

    private void sokAlienTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sokAlienTextFieldActionPerformed
        setJComboBox(sokAlienTextField.getText().toString());
    }//GEN-LAST:event_sokAlienTextFieldActionPerformed

    private void sokAlienButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sokAlienButtonActionPerformed
        sokAlienTextFieldActionPerformed(evt);
    }//GEN-LAST:event_sokAlienButtonActionPerformed

    @SuppressWarnings("unchecked")    
    private void nyAlienRasBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nyAlienRasBoxActionPerformed
        if(nyAlienRasBox.getSelectedItem().equals("Squid")){
            nyAlienExtraAttributLabel.setText("Antal armar:");
            nyAlienExtraAttributLabel.setVisible(true);
            nyAlienExtraAttributTextField.setVisible(true);
        }
        else if(nyAlienRasBox.getSelectedItem().equals("Boglodite")){
            nyAlienExtraAttributLabel.setText("Antal boogies:");
            nyAlienExtraAttributLabel.setVisible(true);
            nyAlienExtraAttributTextField.setVisible(true);
        }
        else{
            nyAlienExtraAttributLabel.setVisible(false);
            nyAlienExtraAttributTextField.setText("1");
            nyAlienExtraAttributTextField.setVisible(false);
        }
    }//GEN-LAST:event_nyAlienRasBoxActionPerformed
    @SuppressWarnings("unchecked")    
    private void nyAlienOmradesBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nyAlienOmradesBoxActionPerformed
        DefaultComboBoxModel platsBox = new DefaultComboBoxModel();
        
        try{
            ArrayList<String> platser = db.fetchColumn("SELECT BENAMNING FROM PLATS WHERE FINNS_I = (SELECT OMRADES_ID FROM OMRADE WHERE BENAMNING = '" + nyAlienOmradesBox.getSelectedItem().toString() + "')" );
            String[] alienSök = valjSoktAlienBox.getSelectedItem().toString().split(" ");
            int alienID = Integer.parseInt(alienSök[1]);
            int nyFinnsI = Integer.parseInt(db.fetchSingle("SELECT OMRADES_ID FROM OMRADE WHERE BENAMNING = '" + nyAlienOmradesBox.getSelectedItem().toString() + "'"));
            setAnsvarigAgentBoxen(alienID, nyFinnsI);
            for(String platsen : platser ){
                platsBox.addElement(platsen);
            }
            nyAlienPlatsBox.setModel(platsBox);
        }
        catch (InfException undantag){
        
        }
    }//GEN-LAST:event_nyAlienOmradesBoxActionPerformed

        @SuppressWarnings("unchecked")
    private void taBortAlienButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taBortAlienButtonActionPerformed
        if (Validering.iDIfyllt(nyAlienIDTextField, valjSoktAlienBox)){
        }
        else{
            String[] alienSök = valjSoktAlienBox.getSelectedItem().toString().split(" ");
            int alienID = Integer.parseInt(alienSök[1]);
            String gammalRas = alienSök[7];

            deleteAlien(alienID, gammalRas);
            JOptionPane.showMessageDialog(null, "Alien har raderats!");
            sokAlienTextField.setText("");
            sokAlienTextFieldActionPerformed(evt);
            valjSoktAlienBoxActionPerformed(evt);
        }
    }//GEN-LAST:event_taBortAlienButtonActionPerformed

    private void nyAlienRegistreringsdatumTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nyAlienRegistreringsdatumTextFieldActionPerformed

    }//GEN-LAST:event_nyAlienRegistreringsdatumTextFieldActionPerformed

    @SuppressWarnings("unchecked")
    private void setJComboBox(String söktNamn){
        try{
        ArrayList<HashMap<String,String>> alien = db.fetchRows("SELECT * FROM ALIEN WHERE NAMN = '" + söktNamn + "'");
        DefaultComboBoxModel söktaAlienTillComboBox = new DefaultComboBoxModel();
        if (alien == null){
            söktaAlienTillComboBox.addElement("---");
        }
        else{
            for(HashMap listaAlien : alien){
                String ras = "Boglodite";
                String rasIdentifierare = db.fetchSingle("SELECT ANTAL_BOOGIES FROM BOGLODITE WHERE ALIEN_ID = " + listaAlien.get("ALIEN_ID"));
                if(rasIdentifierare == null){
                    ras = "Squid";
                    rasIdentifierare = db.fetchSingle("SELECT ANTAL_ARMAR FROM SQUID WHERE ALIEN_ID = " + listaAlien.get("ALIEN_ID"));
                    if (rasIdentifierare == null){
                        ras = "Worm";
                    }
                }
                
                String varjeAlien = "AlienID: " + listaAlien.get("ALIEN_ID") + " | Plats: " +  db.fetchSingle("SELECT BENAMNING FROM PLATS WHERE PLATS_ID = " + listaAlien.get("PLATS")) + " | Ras: " + ras;
                if (ras.equals("Boglodite")){
                    varjeAlien += " | Antal boogies: " + rasIdentifierare;
                }
                else if(ras.equals("Squid")){
                    varjeAlien += " | Antal armar: " + rasIdentifierare;            
                }
                söktaAlienTillComboBox.addElement(varjeAlien);
            }
        }
        valjSoktAlienBox.setModel(söktaAlienTillComboBox);
        }
        catch(InfException undantag){
            System.out.println("Fel med databasen!" + undantag);
        }
        
    }
    @SuppressWarnings("unchecked")    
    private void deleteAlien(int alienID, String gammalRas){
        try{
                db.delete("DELETE FROM " + gammalRas + " WHERE ALIEN_ID = " + alienID);
                db.delete("DELETE FROM ALIEN WHERE ALIEN_ID = " + alienID);    
        }
        catch(InfException undantag){
            System.out.println("KUNDE INTE TA BORT ALIEN! " + undantag);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel angeInfoLabel;
    private javax.swing.JButton avbrytButton;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel mibPortalLabel;
    private javax.swing.JComboBox<String> nyAlienAnsvarigAgentBox;
    private javax.swing.JLabel nyAlienExtraAttributLabel;
    private javax.swing.JTextField nyAlienExtraAttributTextField;
    private javax.swing.JLabel nyAlienIDLabel;
    private javax.swing.JTextField nyAlienIDTextField;
    private javax.swing.JLabel nyAlienLosenordLabel;
    private javax.swing.JTextField nyAlienLosenordTextField;
    private javax.swing.JLabel nyAlienNamnLabel;
    private javax.swing.JTextField nyAlienNamnTextField;
    private javax.swing.JLabel nyAlienOmradeLabel;
    private javax.swing.JComboBox<String> nyAlienOmradesBox;
    private javax.swing.JComboBox<String> nyAlienPlatsBox;
    private javax.swing.JLabel nyAlienPlatsLabel;
    private javax.swing.JComboBox<String> nyAlienRasBox;
    private javax.swing.JLabel nyAlienRasLabel;
    private javax.swing.JLabel nyAlienRegistreringsdatumLabel;
    private javax.swing.JTextField nyAlienRegistreringsdatumTextField;
    private javax.swing.JLabel nyAlienTelefonLabel;
    private javax.swing.JTextField nyAlienTelefonTextField;
    private javax.swing.JLabel nyAnsvarigAgentLabel;
    private javax.swing.JLabel sidLabel;
    private javax.swing.JPanel sidPanel;
    private javax.swing.JSeparator skiljeStreck1;
    private javax.swing.JSeparator skiljeStreck2;
    private javax.swing.JSeparator skiljeStreck3;
    private javax.swing.JSeparator skiljeStreck4;
    private javax.swing.JButton sokAlienButton;
    private javax.swing.JTextField sokAlienTextField;
    private javax.swing.JLabel soktAlienLabel;
    private javax.swing.JButton sparaUppdateradInfoButton;
    private javax.swing.JButton taBortAlienButton;
    private javax.swing.JLabel valjAlienLabel;
    private javax.swing.JComboBox<String> valjSoktAlienBox;
    // End of variables declaration//GEN-END:variables
}
