/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;

/**
 *
 * @author MarcusSkarud
 */
// Denna klass gör inget mer än att visa information om utvecklarna och källa för bilderna.
public class Credits extends javax.swing.JFrame {

    /**
     * Creates new form Credits
     */
    public Credits() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidPanel = new javax.swing.JPanel();
        agentIkonLabel = new javax.swing.JLabel();
        alienIkonLabel = new javax.swing.JLabel();
        copyrightLabel = new javax.swing.JLabel();
        headerLabel = new javax.swing.JLabel();
        utvecklareLabel = new javax.swing.JPanel();
        utvecklare1Label = new javax.swing.JLabel();
        utvecklare2Label = new javax.swing.JLabel();
        utvecklare3Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        sidPanel.setBackground(new java.awt.Color(180, 180, 180));

        agentIkonLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agentIkon.png"))); // NOI18N
        agentIkonLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        alienIkonLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alienIkon.png"))); // NOI18N
        alienIkonLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        copyrightLabel.setForeground(new java.awt.Color(0, 0, 0));
        copyrightLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        copyrightLabel.setText("Icons made by Freepik from www.flaticon.com");

        headerLabel.setBackground(new java.awt.Color(60, 60, 60));
        headerLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(250, 250, 250));
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("Utvecklare");
        headerLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        headerLabel.setOpaque(true);

        utvecklareLabel.setBackground(new java.awt.Color(160, 160, 160));
        utvecklareLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        utvecklare1Label.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        utvecklare1Label.setForeground(new java.awt.Color(0, 0, 0));
        utvecklare1Label.setText("Marcus Skårud");

        utvecklare2Label.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        utvecklare2Label.setForeground(new java.awt.Color(0, 0, 0));
        utvecklare2Label.setText("Jakob Can");

        utvecklare3Label.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        utvecklare3Label.setForeground(new java.awt.Color(0, 0, 0));
        utvecklare3Label.setText("Sebastian Kamsties");

        javax.swing.GroupLayout utvecklareLabelLayout = new javax.swing.GroupLayout(utvecklareLabel);
        utvecklareLabel.setLayout(utvecklareLabelLayout);
        utvecklareLabelLayout.setHorizontalGroup(
            utvecklareLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(utvecklareLabelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(utvecklareLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(utvecklare1Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(utvecklare3Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(utvecklare2Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        utvecklareLabelLayout.setVerticalGroup(
            utvecklareLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(utvecklareLabelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(utvecklare1Label)
                .addGap(18, 18, 18)
                .addComponent(utvecklare2Label)
                .addGap(18, 18, 18)
                .addComponent(utvecklare3Label)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout sidPanelLayout = new javax.swing.GroupLayout(sidPanel);
        sidPanel.setLayout(sidPanelLayout);
        sidPanelLayout.setHorizontalGroup(
            sidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidPanelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(agentIkonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(alienIkonLabel)
                        .addGap(45, 45, 45))
                    .addComponent(utvecklareLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(copyrightLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sidPanelLayout.setVerticalGroup(
            sidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(headerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(utvecklareLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(sidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alienIkonLabel)
                    .addComponent(agentIkonLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(copyrightLabel))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agentIkonLabel;
    private javax.swing.JLabel alienIkonLabel;
    private javax.swing.JLabel copyrightLabel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel sidPanel;
    private javax.swing.JLabel utvecklare1Label;
    private javax.swing.JLabel utvecklare2Label;
    private javax.swing.JLabel utvecklare3Label;
    private javax.swing.JPanel utvecklareLabel;
    // End of variables declaration//GEN-END:variables
}
