/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.DefaultComboBoxModel;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author MarcusSkarud
 */
public class LanaUtrustning extends javax.swing.JFrame {

    private static InfDB db;
    private String agentID;
    /**
     * Creates new form LanaUtrustning
     */
    public LanaUtrustning(InfDB db, String agentID) {
        this.db = db;
        this.agentID = agentID;
        initComponents();
        


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        utrustningsButtonGroup = new javax.swing.ButtonGroup();
        sidPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        mibPortalLabel = new javax.swing.JLabel();
        sidLabel = new javax.swing.JLabel();
        skiljeStreck1 = new javax.swing.JSeparator();
        bodyPanel = new javax.swing.JPanel();
        onskadUtrustningLabel = new javax.swing.JLabel();
        vapenRadioButton = new javax.swing.JRadioButton();
        kommunikationRadioButton = new javax.swing.JRadioButton();
        teknikRadioButton = new javax.swing.JRadioButton();
        ledigUtrustningLabel = new javax.swing.JLabel();
        ledigUtrustningBox = new javax.swing.JComboBox<>();
        lanaUtrustningButton = new javax.swing.JButton();
        avbrytButton = new javax.swing.JButton();
        skiljeStreck2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        sidPanel.setBackground(new java.awt.Color(40, 40, 40));

        headerPanel.setBackground(new java.awt.Color(80, 80, 80));
        headerPanel.setPreferredSize(new java.awt.Dimension(1095, 100));

        headerLabel.setBackground(new java.awt.Color(120, 120, 120));
        headerLabel.setFont(new java.awt.Font("Lucida Grande", 0, 28)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(200, 200, 200));
        headerLabel.setText("Men in Black - Sektor Skandinavien");

        mibPortalLabel.setBackground(new java.awt.Color(120, 120, 120));
        mibPortalLabel.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        mibPortalLabel.setForeground(new java.awt.Color(200, 200, 200));
        mibPortalLabel.setText("MiB-Portalen");

        sidLabel.setBackground(new java.awt.Color(120, 120, 120));
        sidLabel.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        sidLabel.setForeground(new java.awt.Color(200, 200, 200));
        sidLabel.setText("L�na utrustning");

        skiljeStreck1.setForeground(new java.awt.Color(200, 200, 200));

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(mibPortalLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sidLabel)
                        .addGap(39, 39, 39))
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(skiljeStreck1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(headerLabel))
                        .addContainerGap(33, Short.MAX_VALUE))))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(headerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(skiljeStreck1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mibPortalLabel)
                    .addComponent(sidLabel))
                .addContainerGap())
        );

        bodyPanel.setBackground(new java.awt.Color(180, 180, 180));
        bodyPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        onskadUtrustningLabel.setForeground(new java.awt.Color(0, 0, 0));
        onskadUtrustningLabel.setText("�nskad utrustning:");

        vapenRadioButton.setBackground(new java.awt.Color(180, 180, 180));
        utrustningsButtonGroup.add(vapenRadioButton);
        vapenRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        vapenRadioButton.setText("Vapen");
        vapenRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vapenRadioButtonActionPerformed(evt);
            }
        });

        kommunikationRadioButton.setBackground(new java.awt.Color(180, 180, 180));
        utrustningsButtonGroup.add(kommunikationRadioButton);
        kommunikationRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        kommunikationRadioButton.setText("Kommunikation");
        kommunikationRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kommunikationRadioButtonActionPerformed(evt);
            }
        });

        teknikRadioButton.setBackground(new java.awt.Color(180, 180, 180));
        utrustningsButtonGroup.add(teknikRadioButton);
        teknikRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        teknikRadioButton.setText("Teknik");
        teknikRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teknikRadioButtonActionPerformed(evt);
            }
        });

        ledigUtrustningLabel.setForeground(new java.awt.Color(0, 0, 0));
        ledigUtrustningLabel.setText("Ledig utrustning:");

        lanaUtrustningButton.setText("L�na utrustning");
        lanaUtrustningButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lanaUtrustningButtonActionPerformed(evt);
            }
        });

        avbrytButton.setText("Avbryt");
        avbrytButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avbrytButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(lanaUtrustningButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(avbrytButton)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyPanelLayout.createSequentialGroup()
                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(skiljeStreck2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ledigUtrustningBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bodyPanelLayout.createSequentialGroup()
                                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(onskadUtrustningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(bodyPanelLayout.createSequentialGroup()
                                        .addComponent(vapenRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(kommunikationRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(teknikRadioButton))
                                    .addComponent(ledigUtrustningLabel))
                                .addGap(0, 162, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(onskadUtrustningLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vapenRadioButton)
                    .addComponent(kommunikationRadioButton)
                    .addComponent(teknikRadioButton))
                .addGap(4, 4, 4)
                .addComponent(skiljeStreck2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(ledigUtrustningLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ledigUtrustningBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lanaUtrustningButton)
                    .addComponent(avbrytButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout sidPanelLayout = new javax.swing.GroupLayout(sidPanel);
        sidPanel.setLayout(sidPanelLayout);
        sidPanelLayout.setHorizontalGroup(
            sidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
            .addGroup(sidPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sidPanelLayout.setVerticalGroup(
            sidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidPanelLayout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("unchecked")    
    private void vapenRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vapenRadioButtonActionPerformed
        DefaultComboBoxModel utrustningTillComboBox = new DefaultComboBoxModel();
    
        try{
        ArrayList<HashMap<String,String>> ledigaVapen = db.fetchRows("SELECT * FROM UTRUSTNING JOIN VAPEN ON VAPEN.UTRUSTNINGS_ID=UTRUSTNING.UTRUSTNINGS_ID WHERE UTRUSTNING.UTRUSTNINGS_ID NOT IN (SELECT UTRUSTNINGS_ID FROM INNEHAR_UTRUSTNING)");
        for(HashMap ledigtVapen : ledigaVapen){
            String resultat = "ID: " + ledigtVapen.get("UTRUSTNINGS_ID") + " | Namn: " + ledigtVapen.get("BENAMNING") + " | Kaliber: " + ledigtVapen.get("KALIBER");
            utrustningTillComboBox.addElement(resultat);
        }

        }
        catch(InfException undantag){
        
        }
        
        ledigUtrustningBox.setModel(utrustningTillComboBox);
    }//GEN-LAST:event_vapenRadioButtonActionPerformed

    @SuppressWarnings("unchecked")    
    private void kommunikationRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kommunikationRadioButtonActionPerformed
        DefaultComboBoxModel utrustningTillComboBox = new DefaultComboBoxModel();
        
        try{
        ArrayList<HashMap<String,String>> ledigaKomm = db.fetchRows("SELECT * FROM UTRUSTNING JOIN KOMMUNIKATION ON KOMMUNIKATION.UTRUSTNINGS_ID=UTRUSTNING.UTRUSTNINGS_ID WHERE UTRUSTNING.UTRUSTNINGS_ID NOT IN (SELECT UTRUSTNINGS_ID FROM INNEHAR_UTRUSTNING)");
        for(HashMap ledigKomm : ledigaKomm){
            String resultat = "ID: " + ledigKomm.get("UTRUSTNINGS_ID") + " | Namn: " + ledigKomm.get("BENAMNING") + " | Överföringsteknik: " + ledigKomm.get("OVERFORINGSTEKNIK");
            utrustningTillComboBox.addElement(resultat);
        }

        }
        catch(InfException undantag){
        
        }
        
        ledigUtrustningBox.setModel(utrustningTillComboBox);                                            
    }//GEN-LAST:event_kommunikationRadioButtonActionPerformed

    @SuppressWarnings("unchecked")    
    private void teknikRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teknikRadioButtonActionPerformed
        DefaultComboBoxModel utrustningTillComboBox = new DefaultComboBoxModel();

        try{
        ArrayList<HashMap<String,String>> ledigTeknik = db.fetchRows("SELECT * FROM UTRUSTNING JOIN TEKNIK ON TEKNIK.UTRUSTNINGS_ID=UTRUSTNING.UTRUSTNINGS_ID WHERE UTRUSTNING.UTRUSTNINGS_ID NOT IN (SELECT UTRUSTNINGS_ID FROM INNEHAR_UTRUSTNING)");
        for(HashMap ledigaTekniken : ledigTeknik){
            String resultat = "ID: " + ledigaTekniken.get("UTRUSTNINGS_ID") + " | Namn: " + ledigaTekniken.get("BENAMNING") + " | Kraftkälla: " + ledigaTekniken.get("KRAFTKALLA");
            utrustningTillComboBox.addElement(resultat);
        }

        }
        catch(InfException undantag){
        
        }
        
        ledigUtrustningBox.setModel(utrustningTillComboBox);
    }//GEN-LAST:event_teknikRadioButtonActionPerformed

    private void avbrytButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avbrytButtonActionPerformed
        LanaUtrustning.this.dispose();
    }//GEN-LAST:event_avbrytButtonActionPerformed

    private void lanaUtrustningButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lanaUtrustningButtonActionPerformed
        String[] valdUtrustning = ledigUtrustningBox.getSelectedItem().toString().split(" ");
        int utrustningsID = Integer.parseInt(valdUtrustning[1]);
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        Date nyttDatum = new Date();
        String utkvitteringsdatum = dateFormat.format(nyttDatum);
        try{
            db.insert("INSERT INTO INNEHAR_UTRUSTNING VALUES ( " + agentID + " , " + utrustningsID + " , \'" + utkvitteringsdatum + "\')");
            JOptionPane.showMessageDialog(null, "Utrustningslån genomfört!");
        }
        catch(InfException undantag){
            JOptionPane.showMessageDialog(null, "Utrustningslån kunde inte genomföras!");
        
        }

    }//GEN-LAST:event_lanaUtrustningButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton avbrytButton;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JRadioButton kommunikationRadioButton;
    private javax.swing.JButton lanaUtrustningButton;
    private javax.swing.JComboBox<String> ledigUtrustningBox;
    private javax.swing.JLabel ledigUtrustningLabel;
    private javax.swing.JLabel mibPortalLabel;
    private javax.swing.JLabel onskadUtrustningLabel;
    private javax.swing.JLabel sidLabel;
    private javax.swing.JPanel sidPanel;
    private javax.swing.JSeparator skiljeStreck1;
    private javax.swing.JSeparator skiljeStreck2;
    private javax.swing.JRadioButton teknikRadioButton;
    private javax.swing.ButtonGroup utrustningsButtonGroup;
    private javax.swing.JRadioButton vapenRadioButton;
    // End of variables declaration//GEN-END:variables
}
