/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.ArrayList;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.text.DateFormat;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author MarcusSkarud
 */
public class RegistreraAgent extends javax.swing.JFrame {

    private static InfDB db;
    private static Random randGenerator = new Random();
    /**
     * Creates new form BytLosenord
     */
    public RegistreraAgent(InfDB db) {
        this.db = db;
        initComponents();
        setOmradesBox();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        header5 = new javax.swing.JPanel();
        headerLbl5 = new javax.swing.JLabel();
        mibpLbl5 = new javax.swing.JLabel();
        sidLbl5 = new javax.swing.JLabel();
        skiljestreck5 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        omradesBox = new javax.swing.JComboBox<>();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(540, 475));

        jPanel2.setBackground(new java.awt.Color(40, 40, 40));

        header5.setBackground(new java.awt.Color(80, 80, 80));
        header5.setPreferredSize(new java.awt.Dimension(1095, 100));

        headerLbl5.setBackground(new java.awt.Color(120, 120, 120));
        headerLbl5.setFont(new java.awt.Font("Lucida Grande", 0, 28)); // NOI18N
        headerLbl5.setForeground(new java.awt.Color(200, 200, 200));
        headerLbl5.setText("Men in Black - Sektor Skandinavien");

        mibpLbl5.setBackground(new java.awt.Color(120, 120, 120));
        mibpLbl5.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        mibpLbl5.setForeground(new java.awt.Color(200, 200, 200));
        mibpLbl5.setText("MiB-Portalen");

        sidLbl5.setBackground(new java.awt.Color(120, 120, 120));
        sidLbl5.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        sidLbl5.setForeground(new java.awt.Color(200, 200, 200));
        sidLbl5.setText("Nyregistrera Agent");

        skiljestreck5.setForeground(new java.awt.Color(200, 200, 200));

        javax.swing.GroupLayout header5Layout = new javax.swing.GroupLayout(header5);
        header5.setLayout(header5Layout);
        header5Layout.setHorizontalGroup(
            header5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(header5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(header5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(mibpLbl5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sidLbl5)
                        .addGap(39, 39, 39))
                    .addGroup(header5Layout.createSequentialGroup()
                        .addGroup(header5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(skiljestreck5, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(headerLbl5))
                        .addContainerGap(33, Short.MAX_VALUE))))
        );
        header5Layout.setVerticalGroup(
            header5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header5Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(headerLbl5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(skiljestreck5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(header5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mibpLbl5)
                    .addComponent(sidLbl5))
                .addContainerGap())
        );

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(170, 170, 170));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Namn:");
        jLabel1.setPreferredSize(new java.awt.Dimension(110, 16));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Telefon:");
        jLabel2.setPreferredSize(new java.awt.Dimension(110, 16));

        jTextField2.setPreferredSize(new java.awt.Dimension(110, 24));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Område:");
        jLabel3.setPreferredSize(new java.awt.Dimension(110, 16));

        omradesBox.setPreferredSize(new java.awt.Dimension(110, 26));
        omradesBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                omradesBoxActionPerformed(evt);
            }
        });

        jButton1.setText("Nyregistrera Agent");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Avbryt");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jCheckBox1.setBackground(new java.awt.Color(170, 170, 170));
        jCheckBox1.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox1.setText("Administratör");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(omradesBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 200, Short.MAX_VALUE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(omradesBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(header5, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jSeparator5)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(header5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 533, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setBounds(0, 0, 533, 484);
    }// </editor-fold>//GEN-END:initComponents

    private void omradesBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_omradesBoxActionPerformed
        
    }//GEN-LAST:event_omradesBoxActionPerformed
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (Validering.textNotEmpty(jTextField1) && Validering.textNotEmpty(jTextField2)){                
            
            
            int nyAgentID = 0;
            String namn = "";
            int omradesID = 0;
            String anstallningsdatum = "";
            String lösenord = "";
            String telefon = "";
            String omrade = omradesBox.getSelectedItem().toString();
            String administratör = "";
            String ärAdmin = "";
            if (jCheckBox1.getSelectedObjects() == null){
                administratör = "N";
                ärAdmin = "Nej";
            }
            else{
                administratör = "J";
                ärAdmin = "Ja";
            }

            try{
                nyAgentID = Integer.parseInt(db.getAutoIncrement("AGENT", "AGENT_ID"));

                System.out.println(1);
                DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
                Date nyttDatum = new Date();
                anstallningsdatum = dateFormat.format(nyttDatum);

                lösenord = "" + randGenerator.nextInt(10) + randGenerator.nextInt(10) + randGenerator.nextInt(10) +randGenerator.nextInt(10) +randGenerator.nextInt(10) + randGenerator.nextInt(10);
                namn = jTextField1.getText();
                telefon = jTextField2.getText();

                omradesID = Integer.parseInt(db.fetchSingle("SELECT OMRADES_ID FROM OMRADE WHERE BENAMNING = '" + omradesBox.getSelectedItem().toString() + "'"));
                omrade = db.fetchSingle("SELECT BENAMNING FROM OMRADE WHERE OMRADES_ID = " + omradesID);
                System.out.println(2);
                
                db.insert("INSERT INTO AGENT VALUES("+ nyAgentID + ", \'" + namn + "\' , \'" + telefon + "\', \'" + anstallningsdatum + "\', \'" + administratör + "\', \'" + lösenord + "\', " + omradesID + ")");
                System.out.println(3);
                
                JOptionPane.showMessageDialog(null, "Ny agent registrerad!" +
                    "\n\nNamn: " + namn + 
                    "\n\nAgentID: " + nyAgentID + 
                    "\nLösenord: " + lösenord + 
                    "\nTelefon: " + telefon + 
                    "\n\nAnställningsdatum: " + anstallningsdatum + 
                    "\nOmråde: " + omrade + 
                    "\nAdministratör: " + ärAdmin);
                RegistreraAgent.this.dispose();        
            
            }
            catch(InfException undantag){
                JOptionPane.showMessageDialog(null, "Något gick fel med registreringen!");
                System.out.println(undantag);
            }
                
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        RegistreraAgent.this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    @SuppressWarnings("unchecked")    
    private void setOmradesBox(){
        DefaultComboBoxModel omraden = new DefaultComboBoxModel();
        try{
            ArrayList<String> omradesLista = db.fetchColumn("SELECT BENAMNING FROM OMRADE");
            for (String omrade : omradesLista){
                omraden.addElement(omrade);
            }
            omradesBox.setModel(omraden);
            omradesBox.setSelectedIndex(1);
        }
        catch(InfException undantag){
            System.out.println(undantag);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel header5;
    private javax.swing.JLabel headerLbl5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel mibpLbl5;
    private javax.swing.JComboBox<String> omradesBox;
    private javax.swing.JLabel sidLbl5;
    private javax.swing.JSeparator skiljestreck5;
    // End of variables declaration//GEN-END:variables
}
