/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.ArrayList;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.text.DateFormat;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author MarcusSkarud
 */
public class RegistreraAgent extends javax.swing.JFrame {

    private static InfDB db;
    private static Random randGenerator = new Random();
    /**
     * Creates new form BytLosenord
     */
    public RegistreraAgent(InfDB db) {
        this.db = db;
        initComponents();
        setOmradesBox();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        mibPortalLabel = new javax.swing.JLabel();
        sidLabel = new javax.swing.JLabel();
        skiljeStreck1 = new javax.swing.JSeparator();
        skiljeStreck2 = new javax.swing.JSeparator();
        bodyPanel = new javax.swing.JPanel();
        nyAgentNamnLabel = new javax.swing.JLabel();
        nyAgentTelefonLabel = new javax.swing.JLabel();
        nyAgentOmradeLabel = new javax.swing.JLabel();
        nyAgentNamnTextField = new javax.swing.JTextField();
        nyAgentTelefonTextField = new javax.swing.JTextField();
        nyAgentOmradesBox = new javax.swing.JComboBox<>();
        nyAgentAdminCheckBox = new javax.swing.JCheckBox();
        skiljeStreck3 = new javax.swing.JSeparator();
        skiljeStreck4 = new javax.swing.JSeparator();
        registreraNyAgentButton = new javax.swing.JButton();
        avbrytButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(540, 475));

        sidPanel.setBackground(new java.awt.Color(40, 40, 40));

        headerPanel.setBackground(new java.awt.Color(80, 80, 80));
        headerPanel.setPreferredSize(new java.awt.Dimension(1095, 100));

        headerLabel.setBackground(new java.awt.Color(120, 120, 120));
        headerLabel.setFont(new java.awt.Font("Lucida Grande", 0, 28)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(200, 200, 200));
        headerLabel.setText("Men in Black - Sektor Skandinavien");

        mibPortalLabel.setBackground(new java.awt.Color(120, 120, 120));
        mibPortalLabel.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        mibPortalLabel.setForeground(new java.awt.Color(200, 200, 200));
        mibPortalLabel.setText("MiB-Portalen");

        sidLabel.setBackground(new java.awt.Color(120, 120, 120));
        sidLabel.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        sidLabel.setForeground(new java.awt.Color(200, 200, 200));
        sidLabel.setText("Nyregistrera Agent");

        skiljeStreck1.setForeground(new java.awt.Color(200, 200, 200));

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(mibPortalLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sidLabel)
                        .addGap(39, 39, 39))
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(skiljeStreck1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(headerLabel))
                        .addContainerGap(33, Short.MAX_VALUE))))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(headerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(skiljeStreck1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mibPortalLabel)
                    .addComponent(sidLabel))
                .addContainerGap())
        );

        skiljeStreck2.setBackground(new java.awt.Color(0, 0, 0));
        skiljeStreck2.setForeground(new java.awt.Color(255, 255, 255));

        bodyPanel.setBackground(new java.awt.Color(170, 170, 170));
        bodyPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        nyAgentNamnLabel.setForeground(new java.awt.Color(0, 0, 0));
        nyAgentNamnLabel.setText("Namn:");
        nyAgentNamnLabel.setPreferredSize(new java.awt.Dimension(110, 16));

        nyAgentTelefonLabel.setForeground(new java.awt.Color(0, 0, 0));
        nyAgentTelefonLabel.setText("Telefon:");
        nyAgentTelefonLabel.setPreferredSize(new java.awt.Dimension(110, 16));

        nyAgentOmradeLabel.setForeground(new java.awt.Color(0, 0, 0));
        nyAgentOmradeLabel.setText("Område:");
        nyAgentOmradeLabel.setPreferredSize(new java.awt.Dimension(110, 16));

        nyAgentTelefonTextField.setPreferredSize(new java.awt.Dimension(110, 24));

        nyAgentOmradesBox.setPreferredSize(new java.awt.Dimension(110, 26));

        nyAgentAdminCheckBox.setBackground(new java.awt.Color(170, 170, 170));
        nyAgentAdminCheckBox.setForeground(new java.awt.Color(0, 0, 0));
        nyAgentAdminCheckBox.setText("Administratör");

        registreraNyAgentButton.setText("Nyregistrera Agent");
        registreraNyAgentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registreraNyAgentButtonActionPerformed(evt);
            }
        });

        avbrytButton.setText("Avbryt");
        avbrytButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avbrytButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(skiljeStreck3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(skiljeStreck4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nyAgentTelefonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nyAgentOmradeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nyAgentNamnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(nyAgentOmradesBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 200, Short.MAX_VALUE)
                        .addComponent(nyAgentTelefonTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nyAgentNamnTextField, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(nyAgentAdminCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addComponent(registreraNyAgentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(avbrytButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nyAgentNamnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nyAgentNamnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nyAgentTelefonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nyAgentTelefonTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nyAgentOmradeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nyAgentOmradesBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(skiljeStreck3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nyAgentAdminCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(skiljeStreck4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registreraNyAgentButton)
                    .addComponent(avbrytButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout sidPanelLayout = new javax.swing.GroupLayout(sidPanel);
        sidPanel.setLayout(sidPanelLayout);
        sidPanelLayout.setHorizontalGroup(
            sidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidPanelLayout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(skiljeStreck2)
            .addGroup(sidPanelLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sidPanelLayout.setVerticalGroup(
            sidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidPanelLayout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(skiljeStreck2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 533, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setBounds(0, 0, 533, 484);
    }// </editor-fold>//GEN-END:initComponents

    
    // Validering görs om alla nödvändiga fält fyllts i med godkända värden och om så är fallet så registreras en ny agent på
    // nästa lediga AgentID som fås med InfDB:s getAutoIncrement()-metod. Lösenord randomiseras.
    // JOptionPane skapas och visar den nyregistrerade agentens information.
    private void registreraNyAgentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registreraNyAgentButtonActionPerformed
        if (Validering.textNotEmpty(nyAgentNamnTextField) && Validering.textNotEmpty(nyAgentTelefonTextField) &&
            Validering.nameTextFieldLengthCheck(nyAgentNamnTextField) && Validering.checkPhoneLength(nyAgentTelefonTextField)){                
            
            String administratör;
            String ärAdmin;
            if (nyAgentAdminCheckBox.getSelectedObjects() == null){
                administratör = "N";
                ärAdmin = "Nej";
            }
            else{
                administratör = "J";
                ärAdmin = "Ja";
            }

            try{
                int nyAgentID = Integer.parseInt(db.getAutoIncrement("AGENT", "AGENT_ID"));

                DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
                Date nyttDatum = new Date();
                String anstallningsdatum = dateFormat.format(nyttDatum);

                String lösenord = "" + randGenerator.nextInt(10) + randGenerator.nextInt(10) + randGenerator.nextInt(10) +randGenerator.nextInt(10) +randGenerator.nextInt(10) + randGenerator.nextInt(10);
                String namn = nyAgentNamnTextField.getText();
                String telefon = nyAgentTelefonTextField.getText();

                int omradesID = Integer.parseInt(db.fetchSingle("SELECT OMRADES_ID FROM OMRADE WHERE BENAMNING = '" + nyAgentOmradesBox.getSelectedItem().toString() + "'"));
                String omrade = db.fetchSingle("SELECT BENAMNING FROM OMRADE WHERE OMRADES_ID = " + omradesID);
                System.out.println(2);
                
                db.insert("INSERT INTO AGENT VALUES("+ nyAgentID + ", \'" + namn + "\' , \'" + telefon + "\', \'" + anstallningsdatum + "\', \'" + administratör + "\', \'" + lösenord + "\', " + omradesID + ")");
                System.out.println(3);
                
                JOptionPane.showMessageDialog(null, "Ny agent registrerad!" +
                    "\n\nNamn: " + namn + 
                    "\n\nAgentID: " + nyAgentID + 
                    "\nLösenord: " + lösenord + 
                    "\nTelefon: " + telefon + 
                    "\n\nAnställningsdatum: " + anstallningsdatum + 
                    "\nOmråde: " + omrade + 
                    "\nAdministratör: " + ärAdmin);
                RegistreraAgent.this.dispose();        
            
            }
            catch(InfException undantag){
                JOptionPane.showMessageDialog(null, "Något gick fel med registreringen!");
                System.out.println(undantag);
            }
                
        }
    }//GEN-LAST:event_registreraNyAgentButtonActionPerformed

    private void avbrytButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avbrytButtonActionPerformed
        RegistreraAgent.this.dispose();
    }//GEN-LAST:event_avbrytButtonActionPerformed

    //nyAgentOmradesBox:en fylls med databasens alla områden. 
    @SuppressWarnings("unchecked")    
    private void setOmradesBox(){
        DefaultComboBoxModel omraden = new DefaultComboBoxModel();
        try{
            ArrayList<String> omradesLista = db.fetchColumn("SELECT BENAMNING FROM OMRADE");
            for (String omrade : omradesLista){
                omraden.addElement(omrade);
            }
            nyAgentOmradesBox.setModel(omraden);
            nyAgentOmradesBox.setSelectedIndex(1);
        }
        catch(InfException undantag){
            System.out.println(undantag);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton avbrytButton;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel mibPortalLabel;
    private javax.swing.JCheckBox nyAgentAdminCheckBox;
    private javax.swing.JLabel nyAgentNamnLabel;
    private javax.swing.JTextField nyAgentNamnTextField;
    private javax.swing.JLabel nyAgentOmradeLabel;
    private javax.swing.JComboBox<String> nyAgentOmradesBox;
    private javax.swing.JLabel nyAgentTelefonLabel;
    private javax.swing.JTextField nyAgentTelefonTextField;
    private javax.swing.JButton registreraNyAgentButton;
    private javax.swing.JLabel sidLabel;
    private javax.swing.JPanel sidPanel;
    private javax.swing.JSeparator skiljeStreck1;
    private javax.swing.JSeparator skiljeStreck2;
    private javax.swing.JSeparator skiljeStreck3;
    private javax.swing.JSeparator skiljeStreck4;
    // End of variables declaration//GEN-END:variables
}
